// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuQmlVWHeaAqLPTPd4gKBfoQ-PFcOuhE',
    appId: '1:1015472980367:web:cbbf57352fc1564503cbfa',
    messagingSenderId: '1015472980367',
    projectId: 'chatapp-eb04d',
    authDomain: 'chatapp-eb04d.firebaseapp.com',
    storageBucket: 'chatapp-eb04d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIBzpdbrqdSUgUMTgUBmz7A5SReiZNwE',
    appId: '1:1015472980367:android:2a9a1e7d0f541ef803cbfa',
    messagingSenderId: '1015472980367',
    projectId: 'chatapp-eb04d',
    storageBucket: 'chatapp-eb04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArSDKk3CdI2UOaMZX1oRMFTXUpVvoLLIw',
    appId: '1:1015472980367:ios:525fad0d7ba4f10503cbfa',
    messagingSenderId: '1015472980367',
    projectId: 'chatapp-eb04d',
    storageBucket: 'chatapp-eb04d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArSDKk3CdI2UOaMZX1oRMFTXUpVvoLLIw',
    appId: '1:1015472980367:ios:525fad0d7ba4f10503cbfa',
    messagingSenderId: '1015472980367',
    projectId: 'chatapp-eb04d',
    storageBucket: 'chatapp-eb04d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRuQmlVWHeaAqLPTPd4gKBfoQ-PFcOuhE',
    appId: '1:1015472980367:web:5cf9f258f31abf9203cbfa',
    messagingSenderId: '1015472980367',
    projectId: 'chatapp-eb04d',
    authDomain: 'chatapp-eb04d.firebaseapp.com',
    storageBucket: 'chatapp-eb04d.appspot.com',
  );
}
